
DROP TABLE IF EXISTS SHARDING_PROPERTIES;

DROP TABLE IF EXISTS SHARDING_TABLE;

DROP TABLE IF EXISTS SHARDING_ALGORITHMS;

DROP TABLE IF EXISTS SHARDING_DATA_SOURCE;

DROP TABLE IF EXISTS SHARDING_CONFIG;

DROP TABLE IF EXISTS SHARDING_TEMPLATE;

DROP TABLE IF EXISTS SHARDING_TEMPLATE_TYPE;
