
DROP TABLE IF EXISTS DOC_COLLECT;

DROP TABLE IF EXISTS DOC_NODE;

DROP TABLE IF EXISTS DOC_PAGE_DEPT;

DROP TABLE IF EXISTS DOC_PAGE_USER;

DROP TABLE IF EXISTS DOC_PAGE;

DROP TABLE IF EXISTS DOC_BOOK;

DROP TABLE IF EXISTS DOC_FILE;

DROP TABLE IF EXISTS DOC_SIMPLE_TYPE;

DROP TABLE IF EXISTS DOC_SEQUENCE;