
DROP TABLE IF EXISTS REPORT_CONDITION;

DROP TABLE IF EXISTS REPORT_TITLE;

DROP TABLE IF EXISTS REPORT_DESIGN_CATEGORY;

DROP TABLE IF EXISTS REPORT_DESIGN;

DROP TABLE IF EXISTS REPORT_DESIGN_SORT;

DROP TABLE IF EXISTS REPORT_DEFINITION;
