CREATE TABLE CRM_CONTRACT
(
   ID                   BIGINT NOT NULL COMMENT 'ID',
   CODE                 VARCHAR(50) NOT NULL COMMENT '编码',
   NAME                 VARCHAR(255) NOT NULL COMMENT '名称',
   VERSION              VARCHAR(50) NOT NULL COMMENT '版本号',
   CREATE_TIME          DATETIME NOT NULL COMMENT '创建时间',
   UPDATE_TIME          DATETIME NOT NULL COMMENT '更新时间',
   CREATOR_CODE         VARCHAR(50) NOT NULL COMMENT '操作员编码',
   LEAD_ID              BIGINT NOT NULL COMMENT '线索',
   CUSTOMER_ID          BIGINT NOT NULL COMMENT '客户',
   START_TIME           DATETIME NOT NULL COMMENT '开始时间',
   END_TIME             DATETIME NOT NULL COMMENT '结束时间',
   OWNER                VARCHAR(255) NOT NULL COMMENT '负责人',
   AMOUNT               DECIMAL(10,2) DEFAULT 0 COMMENT '合同金额',
   CHECK_STATUS         VARCHAR(255) COMMENT '审批状态',
   TYPE                 VARCHAR(255) NOT NULL COMMENT '类型',
   PROVINCE             VARCHAR(255) COMMENT '省份',
   CITY                 VARCHAR(255) COMMENT '城市',
   AREA                 VARCHAR(255) COMMENT '地区',
   DETAIL               VARCHAR(1000) COMMENT '详细地址',
   PRIMARY KEY (ID)
);

ALTER TABLE CRM_CONTRACT COMMENT '合同';

CREATE UNIQUE INDEX UNIQUE_CODE ON CRM_CONTRACT
(
   CODE
);

CREATE TABLE CRM_CUSTOMER
(
   ID                   BIGINT NOT NULL COMMENT 'ID',
   CODE                 VARCHAR(50) NOT NULL COMMENT '编码',
   NAME                 VARCHAR(255) NOT NULL COMMENT '名称',
   VERSION              VARCHAR(50) NOT NULL COMMENT '版本号',
   CREATE_TIME          DATETIME NOT NULL COMMENT '创建时间',
   UPDATE_TIME          DATETIME NOT NULL COMMENT '更新时间',
   CREATOR_CODE         VARCHAR(50) NOT NULL COMMENT '操作员编码',
   MOBILE               VARCHAR(50) COMMENT '手机号',
   WEBSITE              VARCHAR(255) COMMENT '网址',
   EMAIL                VARCHAR(255) COMMENT '邮箱',
   CHECK_STATUS         VARCHAR(255) COMMENT '审批状态',
   TYPE                 VARCHAR(255) NOT NULL COMMENT '类型',
   PRIMARY KEY (ID)
);

ALTER TABLE CRM_CUSTOMER COMMENT '客户';

CREATE UNIQUE INDEX UNIQUE_CODE ON CRM_CUSTOMER
(
   CODE
);

CREATE TABLE CRM_LEAD
(
   ID                   BIGINT NOT NULL COMMENT 'ID',
   CODE                 VARCHAR(50) NOT NULL COMMENT '编码',
   NAME                 VARCHAR(255) NOT NULL COMMENT '名称',
   VERSION              VARCHAR(50) NOT NULL COMMENT '版本号',
   CREATE_TIME          DATETIME NOT NULL COMMENT '创建时间',
   UPDATE_TIME          DATETIME NOT NULL COMMENT '更新时间',
   CREATOR_CODE         VARCHAR(50) NOT NULL COMMENT '操作员编码',
   MOBILE               VARCHAR(255) COMMENT '手机号码',
   AMOUNT               DECIMAL(10,2) COMMENT '金额',
   BIRTHDAY             DATE COMMENT '生日',
   ADDRESS              VARCHAR(255) COMMENT '地址',
   AGE                  INT(3) COMMENT '年龄',
   SIZE                 DECIMAL(10,2) COMMENT '百分数',
   STATUS               INT(1) COMMENT '状态',
   EMAIL                VARCHAR(255) COMMENT '邮箱',
   EMPLOYEE             VARCHAR(255) COMMENT '员工',
   DEPT                 VARCHAR(255) COMMENT '部门',
   CUSTOMER_ID          BIGINT COMMENT '客户',
   CHECK_STATUS         VARCHAR(255) COMMENT '审批状态',
   SOURCE               VARCHAR(255) COMMENT '来源',
   PRIMARY KEY (ID)
);

ALTER TABLE CRM_LEAD COMMENT '线索';

CREATE UNIQUE INDEX UNIQUE_CODE ON CRM_LEAD
(
   CODE
);

ALTER TABLE CRM_CONTRACT ADD CONSTRAINT FK_CRM_CONTRACT_CUSTOMER FOREIGN KEY (CUSTOMER_ID)
      REFERENCES CRM_CUSTOMER (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CRM_CONTRACT ADD CONSTRAINT FK_CRM_CONTRACT_LEAD FOREIGN KEY (LEAD_ID)
      REFERENCES CRM_LEAD (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CRM_LEAD ADD CONSTRAINT FK_CRM_LEAD_CUSTOMER FOREIGN KEY (CUSTOMER_ID)
      REFERENCES CRM_CUSTOMER (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

