CREATE TABLE SYS_GEN_TABLE_COLUMN_ATTR
(
   COLUMN_ID            BIGINT NOT NULL COMMENT 'ID',
   NAME                 VARCHAR(255) NOT NULL COMMENT '属性key',
   VALUE                VARCHAR(255) NOT NULL COMMENT '属性值',
   PRIMARY KEY (COLUMN_ID, NAME)
);

ALTER TABLE SYS_GEN_TABLE_COLUMN_ATTR COMMENT '代码生成业务字段属性表';

CREATE UNIQUE INDEX UNIQUE_CODE ON SYS_GEN_TABLE_COLUMN_ATTR
(
   NAME
);
