DROP TABLE IF EXISTS SYS_OPERATION_LOG;

DROP TABLE IF EXISTS SYS_MESSAGE;

DROP TABLE IF EXISTS SYS_NOTICE;

DROP TABLE IF EXISTS SYS_NOTICE_EMPLOYEE;

DROP TABLE IF EXISTS SYS_NOTICE_DEPT;

DROP TABLE IF EXISTS SYS_NOTICE_TEMPLATE;

DROP TABLE IF EXISTS SYS_DEPT;

DROP TABLE IF EXISTS SYS_EMPLOYEE_ROLE;

DROP TABLE IF EXISTS SYS_SCENE;

DROP TABLE IF EXISTS SYS_FILE;

DROP TABLE IF EXISTS SYS_COLUMN_SORT;

DROP TABLE IF EXISTS SYS_APP_SORT;

DROP TABLE IF EXISTS SYS_ROLE_PERMISSION;

DROP TABLE IF EXISTS SYS_PRINT_LOG;

DROP TABLE IF EXISTS SYS_PRINT_TEMPLATE;

DROP TABLE IF EXISTS SYS_PERMISSION;

DROP TABLE IF EXISTS SYS_CUSTOM_FIELD;

DROP TABLE IF EXISTS SYS_CUSTOM_FORM;

DROP TABLE IF EXISTS SYS_GEN_TABLE_COLUMN_ATTR;

DROP TABLE IF EXISTS SYS_GEN_TABLE_COLUMN;

DROP TABLE IF EXISTS SYS_GEN_TABLE;

DROP TABLE IF EXISTS SYS_EMPLOYEE;

DROP TABLE IF EXISTS SYS_ROLE;

DROP TABLE IF EXISTS SYS_SEQUENCE;

DROP TABLE IF EXISTS SYS_CONFIG;

DROP TABLE IF EXISTS SYS_DICTIONARIES;

DROP TABLE IF EXISTS SYS_SIMPLE_TYPE;

DROP TABLE IF EXISTS SYS_CODE_GENERATOR;